### ISSUE TITLE
Installation of server

### ISSUE THREAD

**Issue by J-L** [dupes/nebland-oadr-vtn#4]
Do you have a list of instructions I can use to install the server and get it going?

Thanks

John

**Comment by dupes** [comment]
The end of the manual (https://github.com/dupes/nebland-oadr-vtn/blob/gh-pages/images/1026755%20-%20EPRI%20OpenADR%202%200%20Open%20Source%20Virtual%20Top%20Node%20-%20VTN%20Manual.pdf) has basic installation instructions for a production type server.  I don't have instructions for developers yet if that's what you're looking for.  

Or, you can download a VM appliance with the software installed from my website: https://oadrservices.com/downloads.

**Comment by J-L** [comment]
Hey thanks for the support. With those instructions I managed to get it running on a AWS VM with a little prodding.
